### ISSUE TITLE
[Feature]: Upgrade tenant after being restored from lower compatible version cluster to higher

### ISSUE THREAD

**Issue by PowerfooI** [oceanbase/ob-operator#116]
### Describe your use case

It's said in [official document](https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000000218389) that OceanBase after v4.1 supports upgrading tenant from lower version cluster. Maybe it's could be supported in ob-operator.

### Describe the solution you'd like

Add a new type for OBTenantOperation resource. Let user trigger a tenant upgrading job manually.

**Comment by chris-sun-star** [comment]
merged
