### ISSUE TITLE
[Enhancement]: Strengthen validation of webhooks to avoid resources with obviously illegal specification

### ISSUE THREAD

**Issue by PowerfooI** [oceanbase/ob-operator#118]
### Description

ob-operator had better avoid some resources being applied to the cluster. For example, 
1. Create a `OBTenant` which targets at a non-exist `OBClsuter`
2. Create a `OBCluster` with a quite low memory size (like 2Gi)
3. Create a `OBTenantOperation` with a wrong type or wrong parameter

There are so many cases should be avoided ahead of reconciliation in the cluster.

**Comment by chris-sun-star** [comment]
merged
