### ISSUE TITLE
[Feature]: Support startup parameters of observer

### ISSUE THREAD

**Issue by PowerfooI** [oceanbase/ob-operator#126]
### Describe your use case

Observer supports setting startup parameters with `-o` argument according to official document [Deploy OceanBase in Terminal](https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000000220836#5-title-%E6%AD%A5%E9%AA%A4%E4%B8%89%EF%BC%9A%E5%88%9D%E5%A7%8B%E5%8C%96%20OceanBase%20%E6%95%B0%E6%8D%AE%E5%BA%93) and [Cluster-level Parameters](https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000000218691#0-title-%E9%9B%86%E7%BE%A4%E7%BA%A7%E9%85%8D%E7%BD%AE%E9%A1%B9). Maybe it's better to support setting startup parameters in some ways.

### Describe the solution you'd like

1. Add a type for parameters in `OBCluster.Spec.Parameters` to mark those parameters need to be placed in startup options.
2. Add a separate `startupParameters` field in `OBCluster.Spec`

**Comment by chris-sun-star** [comment]
There's not much different when the parameter is set at startup time or after obcluster bootstrapped, so we can just set the parameters at startup time when it is configured before process start
