### ISSUE TITLE
[Feature]: A powerful cli tool

### ISSUE THREAD

**Issue by chris-sun-star** [oceanbase/ob-operator#131]
### Describe your use case

A powerful cli tool to simplify user create and maintain resources

### Describe the solution you'd like

Add a cli tool implementing all the features provided by ob-operator

**Comment by powerfooI** [comment]
We are glad to pronounce the first release of ob-operator CLI tool as `okctl` [here](https://github.com/oceanbase/ob-operator/releases/tag/cli-0.1.0)! 

Great thanks to @lizzy-0323 for continuous devotion for the development of `okctl`.
