### ISSUE TITLE
[Enhancement]: Align cpu quota of resource pool in tenant spec with actual quota of the amount observer gets

### ISSUE THREAD

**Issue by PowerfooI** [oceanbase/ob-operator#151]
### Description

It's kind of ambiguous that `ob-operator` starts `observer` process with 16 Core if we defined a resources.limit.cpu of observer pod less than 16 Core.

**Comment by chris-sun-star** [comment]
what this actually mean, to start observer with cpu_count same as actual limit, or scale the cpu count of tenant with the ratio cpu_count / cpu_limit
