### ISSUE TITLE
[Doc]: Add docs of version 2.1.2

### ISSUE THREAD

**Issue by chris-sun-star** [oceanbase/ob-operator#154]
### Description

 Add docs of version 2.1.2 new features and also docs in English

### Documentation links

https://www.oceanbase.com/docs/ob-operator-doc

**Comment by PowerfooI** [comment]
User manual for ob-operator 2.1.2 has been published on https://en.oceanbase.com/docs/community-ob-operator-doc-en-10000000001137618.

Closed.
