### ISSUE TITLE
[Enhancement]: Support obproxy management in oceanbase-dashboard

### ISSUE THREAD

**Issue by powerfooI** [oceanbase/ob-operator#171]
### Description

There are demonstrations for setting up ODP (OceanBase Database Proxy) in the `examples` while it's a little bit complicated for newbies who are not familiar with OceanBase ecosystem. If a simple configuration entry can be added into spec of `OBCluster`, the obproxy will be more accessible.

**Comment by chris-sun-star** [comment]
for standalone mode, or single node obcluster, there's no need to deploy an odp

**Comment by PowerfooI** [comment]
Maybe we could introduce an `addon` CRD to enable components that lift experience of OceanBase database, which could contain ob-proxy, ob-configserver, oceanbase-dashboard etc..

**Comment by chris-sun-star** [comment]
ob-proxy, ob-configserver and oceanbase-dashboard can be easily deployed using standard deployment or using helm, I don't think it's necessary to add another resource and make ob-operator more complex

for ob-proxy, you can add a management module into oceanbase-dashboard, and for ob-configserver, is it possible to integrate it into oceanbase-dashboard's chart

**Comment by powerfooI** [comment]
Closed due to release of version 0.3.0
