### ISSUE TITLE
使用 NodePort 作为 Service 暴露

### ISSUE THREAD

**Issue by iutx** [oceanbase/ob-operator#31]
### Check Before Asking

- [X] Please check the issue list and confirm this feature is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Description

```markdown
通过 operator 拉起来的 ob cluster 使用 NodePort 作为透出
```

### Other Information

<img width="912" alt="image" src="https://user-images.githubusercontent.com/31346321/210731644-64aa2b22-e067-4f49-93f1-227c05538d84.png">

是否有必要使用 NodePort，这样看起来并不是很安全

**Comment by chris-sun-star** [comment]
Yes, it's not necessary, use clusterip is enough

**Comment by chris-sun-star** [comment]
https://github.com/oceanbase/ob-operator/commit/bb614d87c6c87ffd5e83fcfd9568cab9fa5fb5ef
