### ISSUE TITLE
[Bug]: k8s部署oceanbase4.1时，obcluster.yaml增加新zone，apply后的region与yaml文件里的不一致

### ISSUE THREAD

**Issue by Yuquanchen576** [oceanbase/ob-operator#35]
### Check Before Asking

- [X] Please check the issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
imageRepo: oceanbasedev/oceanbase-cn
  tag: v4.1.0.0-100000192023032010
```

### Fast Reproduce Steps

 使用环境 】 测试环境
![image](https://user-images.githubusercontent.com/132635350/236371217-a462bc92-5313-4910-a8d7-900267f48791.png)
![image](https://user-images.githubusercontent.com/132635350/236371244-8d7d99ec-bb5d-4418-8d65-68ac29dc5dca.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/132635350/236371267-0a5d2b09-2075-4de5-8a69-fd3c024ab89b.png)
![image](https://user-images.githubusercontent.com/132635350/236371287-70e0172e-a2be-426a-bea9-50900166ea1c.png)

**Comment by chris-sun-star** [comment]
region is used to indicate where the zone is located, it only affects the advanced routing policy of obproxy, by checking the code, it's been set when bootstrap, and zone scale progress missed it, if you need the region info to route the request, currently, it can be set using the following sql `alter system alter zone 'zone2' region='region2'`
