### ISSUE TITLE
[Enhancement]: optimize task manager

### ISSUE THREAD

**Issue by chris-sun-star** [oceanbase/ob-operator#37]
on branch 2.0.x_dev
every time a task is submitted, task manager will create a go routine to execute it,  maybe it's a better way to use a coroutine pool, and add timeout for task execution

**Comment by PowerfooI** [comment]
If number of wrong tasks bursts the operator manager will panic, because there is no throttling logic in task manager and task goroutines can be created infinitely. 

Maybe a throttler should be added into TaskManager struct.
