### ISSUE TITLE
[Feature]: open connection in odc sql console for clusters and tenants

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/ob-operator#371]
### Describe your use case

open connection in odc sql console for cluster and tenants.

### Describe the solution you'd like

we can see clusters and tenants in ob-operator console dashboard.
and now mysql command line windows is embeded in cluster page.

what if open connection in odc sql console!
- connect to sys tenant use root user for cluster
- connect to business tenant with selected user

infact odc has ready for integration now, 
legerage odc bastion integraiton, we can use http url paramter to transfer datasource info.
refer details from https://www.oceanbase.com/docs/common-odc-1000000000672287

**Comment by chris-sun-star** [comment]
If everything goes well we will add it in version 0.3.0 of oceanbase-dashboard, otherwise it will be in version 0.4.0

**Comment by powerfooI** [comment]
After the ODC server is deployed, set environment `ODC_URL` of Dashboard to base url of ODC server like `http://xx.xx.xx.xx:yyyy` (or set the variable through `PATCH /api/v1/info` w/o restarting Dashboard pod). A new button to open temporary connection through ODC will appear in `Connection` panel like PR #454 demonstrates.

**Comment by powerfooI** [comment]
Notes: The ODC_URL will be visited in users' browsers, so make sure the URL is accessible.
