### ISSUE TITLE
[Feat.]: add proper event to show the key operation and errors

### ISSUE THREAD

**Issue by chris-sun-star** [oceanbase/ob-operator#38]
### Check Before Asking

- [x] Please check the issue list and confirm this feature is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Description

```markdown
add proper event to show the key operation and errors
```

**Comment by PowerfooI** [comment]
PR #63 adds PrintError method to ResourceManager interface which attaches error information to resource events.
