### ISSUE TITLE
[Feature]: add oceanbase-cluster helm chart to ob-operator helm repo

### ISSUE THREAD

**Issue by willzhang** [oceanbase/ob-operator#390]
### Describe your use case

There is no oceanbase-cluster in ob-operator helm repo.
```
# helm search repo ob-operator
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                         
ob-operator/ob-operator         2.2.1           2.2.1           A Helm chart for OB-Operator        
ob-operator/oceanbase-dashboard 0.2.1           0.2.1           A Helm chart for OceanBase dashboard
```

### Describe the solution you'd like

add oceanbase-cluster helm chart to ob-operator helm repo

**Comment by powerfooI** [comment]
Actually oceanbase-cluster helm charts are there if you `helm search repo ob-operator` with `--devel` option. Due to four-digit version and a build number like `4.2.1.6-106000012024042515` which is not a standard semantic version ([semver](https://semver.org/)), charts of oceanbase cluster are categorized as developing chart. Add `--devel` and you will find them.

**Comment by powerfooI** [comment]
The desired output should be as following,
```shell
$ helm search repo ob-operator --devel
NAME                           	CHART VERSION                	APP VERSION               	DESCRIPTION
ob-operator/ob-operator        	2.2.1                        	2.2.1                     	A Helm chart for OB-Operator
ob-operator/oceanbase-cluster  	4.3.0-sp.1-100000242024032211	4.3.0.1-100000242024032211	A Helm chart for Kubernetes to deploy OceanBase...
ob-operator/oceanbase-dashboard	0.2.1                        	0.2.1                     	A Helm chart for OceanBase dashboard
```

**Comment by willzhang** [comment]
> 所需的输出应如下所示，
> 
> ```shell
> $ helm search repo ob-operator --devel
> NAME                           	CHART VERSION                	APP VERSION               	DESCRIPTION
> ob-operator/ob-operator        	2.2.1                        	2.2.1                     	A Helm chart for OB-Operator
> ob-operator/oceanbase-cluster  	4.3.0-sp.1-100000242024032211	4.3.0.1-100000242024032211	A Helm chart for Kubernetes to deploy OceanBase...
> ob-operator/oceanbase-dashboard	0.2.1                        	0.2.1                     	A Helm chart for OceanBase dashboard
> ```

thanks
