### ISSUE TITLE
[Feature]: support access with service name

### ISSUE THREAD

**Issue by willzhang** [oceanbase/ob-operator#391]
### Describe your use case

There have no service for access oceanbase database, but why?
```
root@node40:~# kubectl -n oceanbase get svc
NAME                                   TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
svc-monitor-oceanbase-cluster-68zvm6   ClusterIP   10.96.2.195   <none>        8088/TCP   26m
```

The introductory tutorial only provides access to services through pod ip. Usually pod ip changes and is difficult to find and 
remember.
```
[10:27:16]After that, the cluster is ready to handle connections stably. Example command is following:
[10:27:16]
[10:27:16]> mysql -A -h$(kubectl get pods -n oceanbase -l ref-obcluster=oceanbase-cluster -o jsonpath='{.items[0].status.podIP}') -P2881 -uroot -p$(kubectl get secret -n oceanbase ob-user-root -o jsonpath='{.data.password}' | base64 -d)
[10:27:16]2024-05-21T10:27:16 info succeeded install app in this cluster
```

In k8s, services are usually accessed using service name, nodeport, loadbalancer or ingress. Why is there no documentation in this regard? Is it not supported?

and how can i access ob database outside the cluster?

### Describe the solution you'd like

support access db with server name , and expose with nodeport、loadbalancer or ingress in obcluster CRD.

### Additional context

similar issue:

- https://github.com/oceanbase/ob-operator/issues/31
- https://github.com/oceanbase/ob-operator/issues/57

**Comment by powerfooI** [comment]
Yes, it's by design. ob-operator does not create services for single observer pods. Instead, you should deploy a proxy (in our case it should be OBProxy for OceanBase) for accessing the distributed database, which is different for accessing single-node database like MySQL. We have put a [`setup-obproxy.sh`](https://github.com/oceanbase/ob-operator/blob/master/scripts/setup-obproxy.sh) in `scripts` folder in master branch. It support setting up proxy for an OBCluster in one step and a service for connecting the cluster.

**Comment by powerfooI** [comment]
Proxy component is commonly necessary for distributed database. This is [documentation](https://www.oceanbase.com/docs/odp-doc-cn) for ODP.

**Comment by powerfooI** [comment]
If you need services for single observer pods, you can set `oceanbase.oceanbase.com/mode` to `service` to bind services for every pod. But this feature require specific oceanbase version, for LTS `4.2.1`, the version should be >= `4.2.1.4`; `4.2.2` DOES NOT SUPPORT the feature; `4.2.3` and `4.3.0` both support this feature.

The document could be found [here](https://oceanbase.github.io/ob-operator/docs/manual/ob-operator-user-guide/high-availability/disaster-recovery-of-ob-operator)
