### ISSUE TITLE
在 DockerHub 上找不到 Tag 以 operator 开头的镜像？

### ISSUE THREAD

**Issue by chenlein** [oceanbase/ob-operator#4]
https://github.com/oceanbase/ob-operator/blob/56c569035218adc2917adba593a698d05b4c5e35/pkg/controllers/observer/const/statefulapp.go#L17

使用 Operator 部署 oceanbase 所使用的镜像与 DockerHub 上的 oceanbase/oceanbase-ce 镜像有区别吗？

**Comment by chris-sun-star** [comment]
https://hub.docker.com/layers/oceanbase-ce/oceanbase/oceanbase-ce/operator-v3.1.3-10100032022041510/images/sha256-6b41b67d2ad28e24440a53ad92fde29b7a0848ce297decaf36f317a8a4fd14d9?context=explore

已经在dockerhub上传了3.1.3版本的docker镜像

operator使用的docker镜像和一般的oceanbase-ce还是有一些区别的，有另外一个进程负责observer进程的拉起
