### ISSUE TITLE
[Feature]: Account and permission management in Dashboard

### ISSUE THREAD

**Issue by powerfooI** [oceanbase/ob-operator#413]
### Describe your use case

Accounts are now simply stored in secret and there is no permission controls in Dashboard. It would be better for users to operate the resources if dashboard offers account and permission management feature.

### Describe the solution you'd like

- `CRUD` for user accounts.
- Control for RBAC permissions.

**Comment by chris-sun-star** [comment]
released in version oceanbase-dashboard-0.3.1
