### ISSUE TITLE
Question - oceanbase version

### ISSUE THREAD

**Issue by Menniti** [oceanbase/ob-operator#418]
Hello,

What is the default version for the oceanbase in this operators? I could found the supported version 4.x but what is the default one?
Thanks in advance

**Comment by powerfooI** [comment]
Hi, Menniti. All versions that ob-operator supports could be found [here](https://hub.docker.com/r/oceanbase/oceanbase-cloud-native/tags?page=&page_size=&ordering=name&name=). Actually there is no default one. We recommend 4.2.1.6 because it is the latest patch version of 4.2.1 LTS.

**Comment by Menniti** [comment]
Got it understood, thanks @powerfooI 
another quick question
Is required some pay license to use it? Or some login in oceanbase cloud or I can use freely?

I’m asking because I’m consider to use it in a personal project that i want to become comercial sooner

**Comment by powerfooI** [comment]
You can use oceanbase community edition for free. For example you create and manage oceanbase database cluster with ob-operator in your own kubernetes cluster. We also offer [oceanbase cloud](https://en.oceanbase.com/docs/common-oceanbase-cloud-10000000000969042), under which is the oceanbase enterprise edition.

By the way, I wonder what feature of oceanbase do you like most, as a user or developer. Thank you @Menniti

**Comment by leo9119** [comment]
@Menniti Thank you very much for your interest in OB. I am a solution architect at OceanBase. I would like to know more about your database usage needs, and I can also assist you in using OBCloud. My email is [ye.hou@oceanbase.com] I'm looking forward to hearing back from you.

**Comment by Menniti** [comment]
Hey guys,

@powerfooI is a several reasons honestly, oltp and olap capabilities in the same database, horizontal scale, and data compression. 
Considering a "standard" solutions around, we will need 2 or 3 databases to fit all those needs that's why i believe this db is huge.

@leo9119, the personal project is a HFT exchange / bot system, i will stream the data into the database. I will not use cloud for now to save costs, for me is very expensive pay stuff in USD dolars, and also the project is not mature enough needs more work from us and than find some clients to make sense get oceanbase cloud or setup a k8s to save some costs

**Comment by powerfooI** [comment]
Thanks a lot. @Menniti
