### ISSUE TITLE
[Question]: oceanbase中使用官方镜像构建失败

### ISSUE THREAD

**Issue by Sangyang-qu8uu** [oceanbase/ob-operator#421]
### Description

![image](https://github.com/oceanbase/ob-operator/assets/53424623/42baebfe-4a73-4c4b-9dae-0abc10d6053a)
使用命令如下：
docker run -p 2881:2881 --name oceanbase-ce -e MODE=slim -e OB_ROOT_PASSWORD="root@123" -e OB_MEMORY_LIMIT=5G -v /usr/local/oceanbase/init/:/root/boot/init.d -d oceanbase/oceanbase-ce

![image](https://github.com/oceanbase/ob-operator/assets/53424623/59453b9e-34f4-4bab-9e2b-875c558aac0c)
我是采纳dockerhub官方文档操作的
![image](https://github.com/oceanbase/ob-operator/assets/53424623/99221878-ddb3-40e8-bf71-e2f9e2525fce)

造成这个原因未知，寻求帮助

**Comment by Sangyang-qu8uu** [comment]
在不添加这个环境-e OB_ROOT_PASSWORD="root@123"能够成功部署

**Comment by powerfooI** [comment]
这个 issue 归属于 docker 镜像，原 issue 被其他同事转移到 [oceanbase/docker-images](https://github.com/oceanbase/docker-images/issues/3) 这个仓库下了，在那边会有相关同事跟进这个问题

**Comment by Sangyang-qu8uu** [comment]
那dockerfile相关的脚本放在什么位置？

**Comment by Sangyang-qu8uu** [comment]
![image](https://github.com/oceanbase/ob-operator/assets/53424623/3f89990f-1458-49d2-bf61-46635e31690f)
这个地方不应该仅仅支持全路径，应该类似 ./xxx/xx当前路径下

**Comment by powerfooI** [comment]
也在那个仓库里，可以看下 [oceanbase-ce](https://github.com/oceanbase/docker-images/tree/main/oceanbase-ce) 目录

**Comment by chris-sun-star** [comment]
你好，如果是想用在生产环境的话请参考我们的文档，使用  ob-operator 配合 oceanbase/oceanbase-cloud-native 的镜像，oceanbase-ce 只是单机版本，适合 demo 使用
