### ISSUE TITLE
[Bug]: Creating an ob cluster in standalone mode takes too long and takes more than 30 minutes to create successfully.

### ISSUE THREAD

**Issue by zrcx123** [oceanbase/ob-operator#486]
### Describe the bug

Creating an ob cluster in standalone mode takes too long and takes more than 30 minutes to create successfully.

### Environment

operator2.2.2
ob cluster in standalone mode

### Fast reproduce steps

Create an ob cluster in standalone mode

**Comment by chris-sun-star** [comment]
PR merged
