### ISSUE TITLE
[Question]: <How to stop OBCluster>

### ISSUE THREAD

**Issue by 66545shiwo** [oceanbase/ob-operator#56]
If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/oceanbase/shared_invite/zt-1e25oz3ol-lJ6YNqPHaKwY_mhhioyEuw)

**Question**
hello, 
I want to know how to stop OBCluster, not delete the OBCluster. I want to keep the pvc data. Thank you !

**Environment**

- OS Version and CPU Arch(`uname -a`):

- Component Version:

**Comment by chris-sun-star** [comment]
There's no proper way to achieve this, ob-operator will detect observer status and do automatic recovery, could you provide your scenario.

**Comment by chris-sun-star** [comment]
close this issue since there's no more reply for a long time
