### ISSUE TITLE
[Bug]: The ob-dashboard is timing out displaying nodes on the dashboard's overview page due to fetching a large number of events that are not OB namespace.

### ISSUE THREAD

**Issue by marsdai** [oceanbase/ob-operator#612]
### Describe the bug

ob-dashboard only need to focus on OB-related namespace, it is recommended to make it configurable, the user can choose OB-related namespace, in addition to get nodes can only get nodes with OB label, for thousands of nodes, I only need to care about hundreds of nodes with OB label.

### Environment

oceanbase-dashboard:0.3.1

### Fast reproduce steps

The ob-dashboard just gets the OB-related namespace and nodes.

**Comment by chris-sun-star** [comment]
We may check the real reason, the log shows that fetching events cost as long as several seconds, but fetching node info costs over 8 minutes.

**Comment by chris-sun-star** [comment]
To optimize this issue, we may fetch the node info asynchronously once the dashboard process starts and trigger background update when the api is called and reached a timeout.

**Comment by powerfooI** [comment]
Closed by PR #615
