### ISSUE TITLE
An extra blank between #! and /usr/ for the first line

### ISSUE THREAD

**Issue by raywill** [oceanbase/ob-operator#619]
https://github.com/oceanbase/ob-operator/blob/1f59638353183c485c4399e4a6f74d79bc41bff8/scripts/setup-obproxy.sh#L1

not sure if this will make the script valid. 

Someone reported that:

> 脚本执行如下：
> bash setup-obproxy.sh -n oceanbase-test1 --proxy-image oceanbase/obproxy-ce:4.2.1.0-11 -d obproxy-test obclusterPS：用/bin/bash执行> 以上shell脚本，用/bin/sh执行报错

**Comment by powerfooI** [comment]
Thank you so much for pointing this out! 

Although there's no evidence showing that the spaces between `#!` and the *interpreter* would cause exception ([SheBang - Wikipedia](https://en.wikipedia.org/wiki/Shebang_(Unix))), we will remove them to align with conventional usage.
